# encoding: UTF-8

FROM <%= ENV.fetch('FROM') %>:<%= ENV.fetch('TAG') %>
MAINTAINER The Blue Beluga <admin@bluebeluga.io>

LABEL vendor="The Blue Beluga Company"
LABEL io.bluebeluga.registry.description="Alpine Linux Registry"
LABEL io.bluebeluga.registry.version="<%= ENV.fetch('TAG') %>"
LABEL io.bluebeluga.registry.git-revision="<%= ENV.fetch('GIT_REVISION') %>"
LABEL io.bluebeluga.registry.release-date="<%= Time.now.strftime('%B %d, %Y %H:%M') %>"

RUN apk-install apache2-utils curl nginx openssl ruby && \
    chown -R nginx:nginx /var/lib/nginx && \
    mkdir -p /etc/nginx/sites-enabled && \
    apk del curl && \
    rm -rf /var/cache/apk/*

COPY files/nginx.conf /etc/nginx/nginx.conf
COPY files/docker-registry-proxy-v2.erb /
COPY files/docker-registry-proxy.erb /
COPY files/registry.sh /

VOLUME /etc/nginx/ssl

EXPOSE 443
CMD ["./registry.sh"]
